### ISSUE TITLE
Recreate Container w/ Latest Image

### ISSUE THREAD

**Issue by regulad** [carlrygart/portainer-stack-deploy#13]
I'm not quite sure if this is possible with the API, but it's worth a shot.

Would it be possible for you to add an option that only recreates a single container, not the whole stack?

![image](https://user-images.githubusercontent.com/52430642/121610358-d4ee8680-ca23-11eb-81be-4b7b61adb235.png)

This option is located in the actions pane for a container.

It can sometimes be better to just redeploy a single container rather than the whole stack.

**Comment by regulad** [comment]
Doesn't seem like it can be done with the API. It's a shame, since it doesn't download the `latest` tag of the image from the registry, meaning that any containers in the stack will still use the same version of the image that they were before.

**Comment by carlrygart** [comment]
Last time I checked, it worked fine to get the latest image by checking the option `Pull latest image` in Portainer. But it's not working for you?

**Comment by regulad** [comment]
?
