### ISSUE TITLE
Environment variables are not kept / reset on updating a stack

### ISSUE THREAD

**Issue by tuxuser** [carlrygart/portainer-stack-deploy#20]
Whenever deploying a stack that has already environment variables set via Portainer UI, they get overriden.

Reason is, that the `updateStack` ([`PUT /stacks/{id}`](https://app.swaggerhub.com/apis/portainer/portainer-ce/2.9.3#/stacks/StackUpdate) Update a stack) method is called without providing the respective parameter `env`.

See:

https://github.com/carlrygart/portainer-stack-deploy/blob/524466cd7956cf9dd1ad2a0554e3cc361b3dabfa/src/deployStack.ts#L86-L92

Portainer API: https://app.swaggerhub.com/apis/portainer/portainer-ce/2.9.3#/stacks/StackUpdate

Example:

```json
{
  "env": [
    {
      "name": "name",
      "value": "value"
    }
  ],
  "stackFileContent": "version: 3\n services:\n web:\n image:nginx"
}
```

A solution to this would be to first fetch the respective by calling [`GET /stacks/{id}`](https://app.swaggerhub.com/apis/portainer/portainer-ce/2.9.3#/stacks/StackInspect) via *existingStack.Id*, then store the Env node in a variable and submit it together with the `stackFileContent` to ([`PUT /stacks/{id}`](https://app.swaggerhub.com/apis/portainer/portainer-ce/2.9.3#/stacks/StackUpdate) aka. `portainerApi.Stacks.updateStack`.

Maybe introduce a parameter to the action like `keep-env`: boolean ?

Is that something worth pursuing?
If so, I would like to propose a PR.

**Comment by carlrygart** [comment]
This sounds reasonable to me. Please proceed with your solution.

I'm leaning towards just making this the default behavior (meaning, skipping the variable). In what situation would it make sense *not* to keep the env variables for your stack when you update a stack? The only risk I can see is if someone has created a separate step in their env variables in another way, and this breaking change would break their pipeline. Any thoughts?

**Comment by tuxuser** [comment]
Right, I cannot really think of a scenario where you would like to ditch already-set environment variables.

**Comment by skraus-dev** [comment]
(Sorry, account mixup..)

Turns out it's even easier - not requiring an additional request to the API.
The desired `Env`-data is already contained in the response to fetch all stacks (`GET /stacks`).

See PR #21
